name: Update RSS Feed

on:
  schedule:
    # Cron: Ogni 3 ore dalle 07:00 alle 22:00 UTC (07:00, 10:00, 13:00, 16:00, 19:00, 22:00)
    - cron: '0 7,10,13,16,19,22 * * *'
  workflow_dispatch: # Permette l'esecuzione manuale

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Imposta Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Versione Python necessaria

      # 3. Installa le dipendenze
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests feedgen

      # 4. Esegui lo script Python
      - name: Run Python Script
        run: python comune_feed_rss.py

      # 5. Commit e push del file RSS aggiornato
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add albo_pretorio_feed.rss
          git commit -m "Update RSS feed via GitHub Actions" || echo "No changes to commit"
          git push
